acp/acp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("dashboard.urls")),
    path("", include("file_upload.urls")),
    path("", include("file_download.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acp/dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("next/", views.home, name="home"),
    path("about/", views.about, name="about"),
]

acp/file_download/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    
    path('download/', views.download, name='download' ),
    path('download-excel/', views.export, name='download-excel'),
]

acp/file_upload/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    
    path('', views.model_form_upload, name="file_upload" )
]

acp/classifier/models.py
from django.db import models

# Create your models here.

acp/file_download/models.py
from django.db import models

# Create your models here.

acp/file_upload/models.py
from django.db import models
from django.db.models.signals import post_save, pre_save
import os
from .validators import validate_file_extension


class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(
        upload_to="documents/", validators=[validate_file_extension]
    )
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.description

    def filename(self):
        return os.path.basename(self.document.name)


class Emotion(models.Model):

    happy = models.IntegerField()
    panic = models.IntegerField()
    bored = models.IntegerField()
    frustrated = models.IntegerField()

acp/file_upload/forms.py
from django import forms
from .models import Document


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = (
            "description",
            "document",
        )
        labels = {
            "document": "SELECT CSV FILE",
            "description": "Input the student number",
        }
        widgets = {"document": forms.FileInput(attrs={"accept": ".csv"})}

acp/classifier/views.py
from django.shortcuts import render

# Create your views here.

acp/dashboard/views.py
from django.shortcuts import render

# Create your views here.
def home(request):

    return render(request, "dashboard/home.html", {"title": "Upload Success"})

def about(request):

    return render(request, "dashboard/about.html", {"title": "About"})

acp/file_download/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .resources import Documents
from file_upload.models import Emotion, Document


def download(request):
    emotion = Emotion.objects.all()
    description = Document.objects.all().order_by("-uploaded_at")[0]
    for e in emotion:
        happy = e.happy
        panic = e.panic
        bored = e.bored
        frustrated = e.frustrated

    if happy > panic and happy > bored and happy > frustrated:
        emotion_1 = "Happy"
        color = "orange"
    elif panic > bored and panic > frustrated:
        emotion_1 = "Panic"
        color = "violet"
    elif bored > frustrated:
        emotion_1 = "Bored"
        color = "gray"
    else:
        emotion_1 = "Frustrated"
        color = "red"

    return render(
        request,
        "file_download/download.html",
        {
            "title": "Download File",
            "happy": happy,
            "panic": panic,
            "bored": bored,
            "frustrated": frustrated,
            "emotion": emotion_1,
            "color": color,
            "description": description,
        },
    )


def export(request):
    document = Documents()
    dataset = document.export()
    response = HttpResponse(dataset.xls, content_type="application/vnd.ms-excel")
    response["Content-Disposition"] = 'attachment; filename="emotions.xls"'
    return response

acp/file_upload/views.py
from django.shortcuts import render, redirect
from .forms import DocumentForm
from .models import Document, Emotion
from django.db.models.signals import post_save, pre_save


import pandas as pd
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk import pos_tag, word_tokenize
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.metrics import confusion_matrix

import csv
from django.conf import settings


def model_form_upload(request):
    if request.method == "POST":
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("home")
    else:
        form = DocumentForm()

    return render(
        request, "file_upload/upload.html", {"form": form, "title": "Upload File",}
    )


def file_upload(sender, instance, **kwargs):
    from sklearn import svm

    instance = instance.document
    root = settings.MEDIA_ROOT
    file_loc = f"{root}/{instance}"
    print(file_loc)
    print(root)
    data = pd.read_csv(
        "C:/Users/Ardy/Desktop/acp\media/documents/xps_edited.csv", encoding="latin-1"
    )
    test_data = pd.read_csv(file_loc, encoding="latin-1")
    happy = 0
    panic = 0
    frustrated = 0
    bored = 0

    # train test split
    X_train, X_test, y_train, y_test = train_test_split(
        data["keystrokes"], data["emotion"], test_size=0.1, random_state=1
    )

    # # training vectorizer
    vectorizer = TfidfVectorizer()
    X_train = vectorizer.fit_transform(X_train)

    # training the classifier
    svm = svm.SVC(C=1000)
    svm.fit(X_train, y_train)

    test = test_data["keystrokes"]

    # testing against testing set
    X_test = vectorizer.transform(test)
    y_pred = svm.predict(X_test)
    # print(confusion_matrix(y_test, y_pred))
    # print(y_pred)

    for y in y_pred:

        if y == "Happy":
            happy += 1
        elif y == "Panic":
            panic += 1
        elif y == "Bored":
            bored += 1
        elif y == "Frustrated":
            frustrated += 1
        else:
            print("Error in your code!")

    emotion = Emotion.objects.get(id=1,)
    emotion.happy = happy
    emotion.panic = panic
    emotion.bored = bored
    emotion.frustrated = frustrated
    emotion.save()

    # print(happy, panic, frustrated, bored)
    # context = {"happy": happy, "panic": panic, "bored": bored, "frustrated": frustrated}


post_save.connect(file_upload, Document)

acp/dashboard/templates/dashboard/about.html
{% extends 'dashboard/base.html' %}
{% block content %}
<div class="container m-3">
  <h1 class="display-4 text-center">Welcome to ACP!</h1>
  <h3>How to use!</h3>
  
  <h5>1. Input the student number </h5>
  <h5>2. Click "Choose File" and select the CSV file </h5>
  <h5>3. Click "Upload" button </h5>
  <h5>4. Click "Next" button </h5>
  <h3>You can now view the result and analysis of the prototype</h3>
  <h2>[OPTIONAL]</h2>
  <h5>Click the "Download as excel file" button to download the result in excel file or</h5>
  <h5>Click the "Upload another file" button to upload new file </h5>
  <div style="background-image: url('C:/Users/Ardy/Desktop/ACP_Images/home.jpg');"></div>
</div>

{% endblock content %}
    

acp/dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="path/to/chartjs/dist/Chart.min.css">

    <title>ACP</title>

    <style>
      body{
        padding: 0%;
        margin: 0;
      }
    </style>



</head>
<body >
    

    <div  style="background: white; width: 100%; height:100vh">
        <nav class="navbar navbar-expand-lg navbar-dark bg-403a40 pl-5 pr-5" style=" background: radial-gradient(orange, #cc8706); width: 100%;">
            <a class="navbar-brand" href="{% url 'file_upload' %}">Affective Computing of Programmers</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
              <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                  
                  <a class="nav-item nav-link active" href="{% url 'about' %}">About</a>
                
                  
                </div>
              </div>
              <span class="navbar-text">
                
                
                {% if title %}
                  {{title}}
                {% endif %}
              </span>
            </div>
          </nav>


            <div class="container-fluid   d-flex justify-content-center" style="padding: 0; margin:0" >
              {% block content %}
               
              {% endblock content %}
              </div>
              
           
          
    </div >

    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
</body>
</html>

acp/dashboard/templates/dashboard/home.html
{% extends 'dashboard/base.html' %}
{% block content %}

<div class=" text-center m-5">

  <h1>UPLOAD SUCCESS</h1>
  <a href="{% url 'download' %}">
    <svg height="250pt" viewBox="-18 -18 572.00902 572" width="250pt" xmlns="http://www.w3.org/2000/svg"><path d="m279.628906 143.855469c-4.851562-4.855469-12.722656-4.855469-17.582031 0-4.855469 4.851562-4.855469 12.726562 0 17.582031l94.164063 94.164062h-250.191407c-6.886719 0-12.472656 5.585938-12.472656 12.472657 0 6.890625 5.585937 12.472656 12.472656 12.472656h250.066407l-94.164063 94.164063c-2.335937 2.328124-3.648437 5.496093-3.648437 8.792968 0 3.300782 1.3125 6.460938 3.648437 8.792969 2.335937 2.355469 5.535156 3.660156 8.855469 3.617187 3.308594-.015624 6.484375-1.3125 8.851562-3.617187l115.367188-115.363281c2.347656-2.351563 3.65625-5.542969 3.621094-8.859375-.023438-3.308594-1.320313-6.472657-3.621094-8.851563zm0 0"/><path d="m268.15625-.0742188c-108.457031-.0195312-206.242188 65.3085938-247.746094 165.5117188-41.496094 100.207031-18.542968 215.542969 58.171875 292.210938 104.703125 104.703124 274.453125 104.703124 379.152344 0 104.699219-104.695313 104.699219-274.445313 0-379.148438-50.167969-50.453125-118.429687-78.746094-189.578125-78.5742188zm0 511.3554688c-134.074219 0-243.203125-109.132812-243.203125-243.207031s109.128906-243.203125 243.203125-243.203125 243.207031 109.128906 243.207031 243.203125-109.132812 243.207031-243.207031 243.207031zm0 0"/></svg>
    
  </a>
  <h1>NEXT</h1>
</div>

{% endblock content %}
    

acp/file_download/templates/file_download/download.html
{% extends 'dashboard/base.html' %}

{% load crispy_forms_tags %}
{% block content %}


<div id="container text-center" style="width: 60%; " class="text-center p-3 ">
    <canvas id="pie-chart">
       
    </canvas>
    <div class="m-3">
        <h3>The outstanding emotion of student <span style="color: blue;">{{description}}</span> is <div style="color: {{color}};">{{emotion}}</div>
            

        </h3>
    </div>
    

    <a href="{% url 'download-excel' %}" >
        <button class="btn btn-primary m-3">Download as excel file</button></a>
    
        <a href="{% url 'file_upload' %}" >
            <button class="btn btn-warning m-3">Upload another file</button></a>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    var config = {
      type: 'doughnut',
      data: {
        datasets: [{
          data: [{{happy}},{{panic}}, {{bored}}, {{frustrated}}],
          backgroundColor: [
            'orange', 'violet', 'gray', 'red', 
          ],
          label: 'Emotions'
        }],
        labels: ['Happy', 'Panic', 'Bored', 'Frustrated']
      },
      options: {
        responsive: true,
        legend: {
            display: true,
            labels: {
                fontColor: 'black',
                
            }
        
            
        },
        tooltips: {
            callbacks: {
                
                labelTextColor: function(tooltipItem, chart) {
                    return 'white';
                }
            }
        }
        
      }
    };

    window.onload = function() {
      var ctx = document.getElementById('pie-chart').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };

  </script>

{% endblock %}

acp/file_upload/templates/file_upload/upload.html
{% extends 'dashboard/base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<style>
    label[for="id_document"]{
      display: inline-block; 
      margin-bottom: .5rem; 
      background: white;
      width: 100% ;
      border-radius: 5px;
      background-color: orange;
    }

    label[for="id_description"]{
      display: inline-block; 
      margin-bottom: .5rem; 
      background: white;
      width: 100% ;
      border-radius: 5px;
      background-color: orange;
    }
    
  </style>
  

    <div class="col-md-auto col-md-6 text-center" style="padding-top: 5rem;">
    
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
  
  
       {{form|crispy}} 
  
       
        <button class="btn btn-warning " style="width: 100%;">Upload</button>
      
      </form>
  
    </div>

  

      
{% endblock %}